dast_scan:
  stage: dast_scan
  image: maven:3.8.5-openjdk-11-slim
  before_script: [] 
  script:
    - apt-get update
    - apt-get -y install wget wkhtmltopdf
    - wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_Linux.tar.gz
    - mkdir zap
    - tar -xvf ZAP_2.15.0_Linux.tar.gz
    - cd ZAP_2.15.0
    - ./zap.sh -cmd -quickurl https://rafaeldesafiodnc.netlify.app/ -quickprogress -quickout ../zap_report.html -config database.reset=true
    - cd ..
    - wkhtmltopdf zap_report.html zap_report.pdf

  artifacts:
    paths:
      - zap_report.pdf
    expire_in: 1 day
  tags:
    - docker
  when: on_success
